### ISSUE TITLE
<input name=foo type=location units=tilematrix axis=row> events for painting vector tiles

### ISSUE THREAD

**Issue by prushforth** [opengeospatial/D012-MapML_Engineering_Report#21]
In HTML [`<input>`](https://developer.mozilla.org/en-US/docs/Web/Events/input)s fire events when they are updated.  This should also be true in MapML, and this will enable script-based handling of panning and zooming-generated events which require, for example, tile content.  

When such an event is generated, the script could retrieve and paint content on the map in a `<tile>` node, for example on a canvas, using content from a vector tile, for example.  Given that the format of vector tiles is not standard today, and may be that way for a long time, if not permanently, this will be an important aspect to a standard for Web maps, since vector tiles are obviously important for users.

I mentioned this idea in issue #18 originally.

**Comment by joanma747** [comment]
I'm concerned about having internal events in MapML. What I understood is that the final goal of MapML is to create a new media type that can be rendered by the web browser directly. In this situation, the format should be opaque and only the browser should be able to interpret it. This way we can escape the CORS (in the same way that <img src=> or <iframe> avoid CORS considerations). I understand this is going to limit capabilities but I find avoiding CORS extremely important. It is vital that we are creating a standard that allows overlapping features from different services easily. This characteristic will make MapML perform better leaflet and others.

IMHO, we should focus on the external events that a mapml file can trigger: the ones that we could associate to <layer> in the map4html level such as onload and onchange. This could eventually allow for a native <map> area (managed by the web browser directly) to interact with a leaflet division (managet by the programmer and the leaflet API). This way pan or zoom in the <map> could trigger an onchange() that could receive the new bbox. Then a JavaScript code could send commands to a leaflet api requesting to synchronize it to the <map> bbox. A expert programmer, can then deal with vector tiles in leaflet. Both leaflet and <map> could be adjacent or overlapped forming a single visual entity from the user perspective

**Comment by prushforth** [comment]
> What I understood is that the final goal of MapML is to create a new media type that can be rendered by the web browser directly.

Indeed, this is true, and it could work with CORS the same way <img src="..."> works with SVG, I think.  

But I also think, and it was mentioned to me in the SDWIG meeting in Fort Collins (and elsewhere), that extensions to browsers that are DOM-compatible are necessarily incorporated into HTML.  SVG is the canonical example of this.  SVG can be used as the source of an <img src"...">, in which case script does not execute (but CSS does) (there are some other limitations of that mode that I believe we will have to analyse), AND it can be used inline in an HTML document, where the <svg> element defines the area on which the graphics are painted. In the latter mode, the DOM is fully exposed and is programmable readable/writable.

>  I understand this is going to limit capabilities 

I think the inline mode allows us to think about building "progressive enhancement" into our proposal, and it is PE which separates us from the 1990's.  Furthermore, by allowing PE into the discussion, we don't have a dead-end proposal: we can say "this is what we want browsers to implement, this other stuff can and should be handled by scripting".   I think vector tiles fall squarely into this category.

I think what we're debating here is "where the line is between what browsers should do and what script should be able to do".  Today in maps, everything is script.  I want to move the line a little bit towards getting the browser to provide some of the mapping infrastructure so that JavaScript libraries can focus on the cool stuff, but not so far that the behaviour of maps is so predetermined that it becomes a dead-end.
