### ISSUE TITLE
Links for alternatives of headers for content negotiation.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/D012-MapML_Engineering_Report#31]
We are using

```
<link rel=crs >
<link rel=crs >
<link rel=crs >

```
to "negotiate" styles but we could use headers too:
Accepted-crs: WGS84, UTM31

In the first approach is the client the one decides about the proposals coming for the server.
In the second approach is the server that decided to serve one of the alternatives proposed by the client.

**Comment by prushforth** [comment]
@6a6d74 [recommended ](https://github.com/w3c/sdw/projects/10#card-11043572 )that we have a look at [profile negotiation](https://profilenegotiation.github.io/I-D-Accept--Schema/I-D-accept-schema#rfc.section.1)

**Comment by pomakis** [comment]
Sounds like a reasonable approach to me.  I'll try to find time within the next few days to implement it in our Testbed-14 MapML server.

The only thing I find jarring about it is that a MapML document indicates its current style and provides links to alternate styles like this:

    <link rel="self style" title="Style1" href="..."/>
    <link rel="style" title="Style2" href="..."/>

but it indicates its current projection and provides links to alternate projections like this:

    <meta name="projection" content="OSMTILE"/>
    <link rel="alternate" projection="CBMTILE" href="..."/>

Perhaps there are justifications for this, but at first glance it just seems like a sloppy inconsistency.

**Comment by prushforth** [comment]
> at first glance it just seems like a sloppy inconsistency

What would you suggest to remove the inconsistency?

**Comment by prushforth** [comment]
> `<link rel="projection" name="CBMTILE" href="..."/>`

Is pretty close to what I implemented, except it adds the 'projection' value to the list of rels and adds the 'name' attribute to the link.  A 'name' attribute is generic, and there is already the 'title' attribute so the presence of both could be confusing perhaps.  The 'alternate' rel value has an [existing definition](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types) that seems close to what is required, as well as the fact that (in HTML) rel=alternate seems to have a modified meaning based on the presence of the media, or hreflang attributes.  I thought a similar mechanism / modification of meaning might be acceptable for the 'projection' attribute.

FWIW I don't love the rel="self style" / multiple rel values structure, but short of actually having a `<select>`  in the head, I couldn't think of another way to identify what the current style was. 

Also CRS negotiation seems more like something we don't really want the user involved in directly if we can help it, whereas having a control to select a style seems more like a user-level decision.

**Comment by pomakis** [comment]
Fair enough.  I'll try to get an implementation up sometime tomorrow.

**Comment by prushforth** [comment]
Cool!

**Comment by pomakis** [comment]
Done!  All of the previously-advertised MapML URLs served from tb14.cubewerx.com now report their alternate projections.

**Comment by prushforth** [comment]
Great! Works well.

**Comment by joanma747** [comment]
It is great that you implemented that. I'm a bit confused about the final agreed solution.

Sorry to arrive late to the discussion but I'm not sure that I like the idea of "self" instead of "alternate" as proposed here for stylesheets:
https://www.w3.org/Style/Examples/007/alternatives.en.html

<link rel="stylesheet"  title="Gold (right, fixed) + navbar"  href="../threepart-f.css">
<link rel="alternate stylesheet"  title="Oldstyle"  href="http://www.w3.org/StyleSheets/Core/Oldstyle">

**Comment by joanma747** [comment]
Just for clarification, the CRS negociation that was finally implemented follows this more simple approach that uses alternate and "projection=":

```
<meta name="projection" content="OSMTILE"/>
<link rel="alternate" projection="CBMTILE" href="https://tb14.cubewerx.com/cubewerx/cubeserv/mapML/wmts/1.0.0/mapML/Foundation.inwatera_1m/cubewerx?projection=CBMTILE"/>
```
I believe this concludes this discussion.
