### ISSUE TITLE
Failure to understand 'input@units' in the table compared with the examples.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/D012-MapML_Engineering_Report#36]
I believe we need more details when the MapML specification (https://maps4html.github.io/MapML/spec/) describes "input@units". I have several issues with this table but going to the point: I would like to talk about 'tilematrix'.
The text in the description is:
"The location should be serialized in units associated to the tilematrix at the zoom level of the extent"
Unfortunatelly "tilematrix" is not defined elsewhere in the document. I can only go to the figure in the annex. There I can learn that "tilematrix" starts in the topleft corner of the tesselation (like "tcrs"). The copied definition seems to suggest that is zoom depended ("...at the zoom level of the...") so it could be in "pixels" but the definition of "tcrs" says that tcrs is in "pixels" so the two things could end up being the same. It could also be just the index of TileRow and TileCol in WMTS (you take the tiles and assign them a number in the i and j direction). Whatever it is exactly, it does not seem projected coordinatates.

Then I try to understand this example: https://geogratis.gc.ca/mapml/en/cbmtile/fdi?alt=xml
```
<input name="z" type="zoom" value="0" min="0" max="18"/>
<input name="projection" type="projection" value="CBMTILE"/>
<input name="txmin" type="location" units="tilematrix" position="top-left" axis="easting"/>
<input name="tymin" type="location" units="tilematrix" position="bottom-left" axis="northing"/>
<input name="txmax" type="location" units="tilematrix" position="top-right" axis="easting"/>
<input name="tymax" type="location" units="tilematrix" position="top-left" axis="northing"/>
<template type="tile" tref="http://maps.nofc.cfs.nrcan.gc.ca/geoserver/public/wms?service=WMS&version=1.1.0&request=GetMap&layers=public:fdr_current&styles=&bbox={txmin},{tymin},{txmax},{tymax}&width=256&height=256&srs=EPSG:3978&FORMAT=image/png&TRANSPARENT=TRUE&m4h=t"/>
```
The "txmin" is defined as "tielmatrix" but it is used in a WMS BBOX (that has to be in projected coordinates. And here is were I have to recognize that I'm completely lost.

Can we produce a more clear definition of the input@units values?.

**Comment by joanma747** [comment]
I have produced my own interpretation of the definition in the MapML specification.

/opengeospatial/D012-MapML_Engineering_Report/blob/master/5-crs.adoc

This will require some discussion. I was very confused by the definition of tcrs and I propose a change in the meaning that I hope is acceptable. For the other definition I tried to keep them as it were but adding clarification. I hope I have not mixed them due to my possible lack of understanding.

**Comment by prushforth** [comment]
Agree that is an oversight. The units are supposed to be for the row and column axes with row=0 col=0 being in the upper left hand corner of the grid, so I suppose the units would have to be "tile", with the coordinate system name being "tilematrix".

Once we've had a discussion I can add a definition to the spec.

**Comment by joanma747** [comment]
Please, consider this 3 issues in the MapML diagram that are all related to the discussion here and the following discussion in the Sept 26th, 2018 telecon.
https://github.com/Maps4HTML/MapML/issues/25
https://github.com/Maps4HTML/MapML/issues/24
https://github.com/Maps4HTML/MapML/issues/23

**Comment by joanma747** [comment]
Since the issue is now moved to the MapML github, I'm closing this one.
