### ISSUE TITLE
GML encoding for points, lines and polygons compared with XML-GeoJSON. The GeoRSS route.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/D012-MapML_Engineering_Report#8]
In order to demonstrate that GML notation for points, lines and polygons is similar to the one obtained in XML-GeoJSON, I'm posting some examples here. My personal opinion is that if OGC has its own model for features that works well, we should not defined a new one even if its based on a recognized JSON equivalent.
This route was also chosen by GeoRSS before: http://www.georss.org/gml.html. As you can see, the document describing the GML profile for GeoRSS is quite simple.

Points in GML:
```
    <Point>
       <pos>123 321</pos>
    </Point>`
```
Points in XML-GeoJSON
```
    <Point>
       <coordinates>123 321</coordinates>
    </Point>
```
----

Lines in GML
```
    <LineString>
       <posList>123 321 122 322</pos>
    </LineString>
```
Lines in XML-GeoJSON
```
    <LineString>
       <coordinates>123 321 122 322</coordinates>
    </LineString>
```
----

Polygons in GML
```
    <Polygon>
      <exterior>
        <LinearRing>
          <posList>123 321 124 322 126 322 123 321
          </posList>
        </LinearRing>
      </exterior>
    </Polygon>
```
Polygons in XML-GeoJSON
```
    <Polygon>
      <coordinates>123 321 124 322 126 322 123 321</coordinates>
    </Polygon>
```
----
Points in GML:
```
<MultiPoint> 
      <pointMember> 
        <Point> 
          <pos>1 1</pos> 
        </Point> 
      </pointMember> 
      <pointMember> 
        <Point> 
          <pos>2 2</pos> 
        </Point> 
      </pointMember> 
<MultiPoint> 
```
Multipoints in XML-GeoJSON
```
    <MultiPoint>
       <coordinates>1 1</coordinates>
       <coordinates>2  2</coordinates>
    </MultiPoint>
```

**Comment by prushforth** [comment]
There does seem to be an issue of me never having implemented multi-geometries resulting in an error in the spec here, though.  

```
MultiPoint 
MultiLineString 
MultiPolygon 
```

The definitions can't exactly follow that of "XML-GeoJSON", or rather we'll need to amend what "XML-GeoJSON" means.  Specifically the content model of those things was specified as two or more `<coordinates>` elements, but unless I'm mistaken, that won't work for `MultiPolygon` at least because a `<coordinates>` element can't contain another <coordinates> element, so there will at least have to be a member-distinguishing child element in that case.  I would not be averse to adding a member-distinguishing element in the cases of `MultiPoint` and `MultiLineString`, although perhaps it could be optional in those cases.

Thoughts?

**Comment by prushforth** [comment]
For multipolygon geometries it works quite well to treat child <polygon> elements as an array, similar to how the <coordinates> children of polygon are themselves treated.  This maps to GeoJSON very conveniently in the Leaflet client code I am using, so I think that is what I'll change the specification to reflect that.  This is consistent with the XML-GeoJSON model.

**Comment by joanma747** [comment]
I'm still uneasy to propose a XML encoding different from GML. At the beginning of this issue I compared the GML with the XML-GeoJSON encoding for geometries and I have demonstrated that the complexity or GML versus XML-GeoJSON is similar if we forget about schemas and we focus on a particular version of GML that we reproduce in the MapML specification. Multipoints, multilines and multipolygons can also be encoded in GML in a much more nice notation. I also thing that transforming from GML to GeoJSON to please Leaflet should not be difficult to do. Another advantage is that GML can be extended easily while GeoJSON is not extensible by definition.

Said that, I believe that the idea of having <coordinates> inside <coordinates> (multiplicity 0 to n) mimics correctly the array inside the array that GeoJSON requires. This is my interpretation of your last post in this issue. In this case <coordinates> will be a mixed content (https://www.w3schools.com/xml/schema_complex_mixed.asp). This is not common in the OGC-ISO world but it is find there. We only need a restriction that says that only the last leaf in <coordinates>can contain values (numbers) while the intermediate nodes should only contain other <coordinates> elements. 

Just to be sure that I'm getting this correctly, @prushforth, can you paste here an example of your solutions for multipolygons?.

**Comment by prushforth** [comment]
[Alaska and a few others are multipolygons.](http://geogratis.gc.ca/api/beta/mapml/static/us_pop_density.html)

**Comment by prushforth** [comment]
```


<feature class="all  _0-10">
   <properties>
     <h1>Alaska</h1>
   </properties>
   <geometry>
     <multipolygon>
       <polygon>
         <coordinates>-131.602021 55.117982 -131.569159 55.28229 -131.355558 55.183705 -131.38842 55.01392 -131.645836 55.035827 -131.602021 55.117982</coordinates>
       </polygon>
       <polygon>
         <coordinates>-131.832052 55.42469 -131.645836 55.304197 -131.749898 55.128935 -131.832052 55.189182 -131.832052 55.42469</coordinates>
       </polygon>
       <polygon>
         <coordinates>-132.976733 56.437924 -132.735747 56.459832 -132.631685 56.421493 -132.664547 56.273616 -132.878148 56.240754 -133.069841 56.333862 -132.976733 56.437924</coordinates>
       </polygon>
       <polygon>...</polygon>
    </multipolygon>
  </geometry>
</feature>

```

**Comment by joanma747** [comment]
Clearly I was not getting it.

A polygon is a sequence of rings (outer and inner). How do you express that?.

How to you express a multipoint?

**Comment by prushforth** [comment]
The outer ring is the first ring, subsequent rings are inner rings, per [GeoJSON encoding](https://tools.ietf.org/html/rfc7946#appendix-A.3)

> How to you express a multipoint?

[Similarly](https://tools.ietf.org/html/rfc7946#appendix-A.4):

<multipoint>
  <point><coordinates>-74.9558219 45.4800402</coordinates></point>
  <point>...</point>
</multipoint>

**Comment by joanma747** [comment]
> > A polygon is a sequence of rings (outer and inner). How do you express that?.
> The outer ring is the first ring, subsequent rings are inner rings, per GeoJSON encoding
I see.
In GeoJSON rings are **separated** arrays of coordinates (i.e. an array of arrays of coordinates). Are you separating the rings somehow or do you assume that when a coordinate is equal to the initial one a ring ends and another one starts?.

**Comment by joanma747** [comment]
Most of the content in this issue has been moved to the ER. I believe we can close the issue
